### ISSUE TITLE
[Feature Request] Some common search operations

### ISSUE THREAD

**Issue by huyz** [aome510/hackernews-TUI#66]
Right now I use https://hn.algolia.com/ to browse the most popular stories of the past week or month.
Would be awesome if these could be added as well to hackernews-TUI.

**Comment by aome510** [comment]
Hi @huyz, `hackernews-TUI` already supports adding a [custom shortcut](https://github.com/aome510/hackernews-TUI/blob/main/config.md#custom-keymap) for searching stories. In fact, it uses `hn.algolia` APIs to do so.

An example config section in `hn-tui.toml` to add `M-1` for past week and `M-2` for past month:
```toml
[[keymap.custom_keymaps]]
key = "M-1"
tag = "story"
by_date = false
[keymap.custom_keymaps.numeric_filters]
elapsed_days_interval = {start = 0, end = 7}

[[keymap.custom_keymaps]]
key = "M-1"
tag = "story"
by_date = false
[keymap.custom_keymaps.numeric_filters]
elapsed_days_interval = {start = 0, end = 30}
```

Please lmk if this does not work.
