### ISSUE TITLE
Is it possible to have a transparent background?

### ISSUE THREAD

**Issue by user451421541757324** [aome510/hackernews-TUI#83]
At the moment, I am able to set a solid color as background:
`[theme.palette]`
`background = "#333333"`

Is it possible to have a transparent one?

**Comment by aome510** [comment]
> Is it possible to have a transparent one?

Yes, it's possible if your terminal supports transparency. You can set the `theme.palette` fg and bg to use the terminal default values:

````toml
background = "default"
foreground = "default"
```
